language: cpp

compiler:
  - gcc
  - clang
  
os:
  - linux
  - osx
  
dist: trusty

addons:
    apt:
        packages:
            - cmake
  
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install libglfw3-dev libglfw3;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install homebrew/core/glfw3;
    fi

before_script:
  - cmake -H. -BBuild

script:
  - cmake --build Build --config Release
